# permissions for end users to view storageconsumerclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storageconsumerclient-viewer-role
rules:
- apiGroups:
  - odf.openshift.io
  resources:
  - storageconsumerclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - odf.openshift.io
  resources:
  - storageconsumerclients/status
  verbs:
  - get
