apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ocs-consumer-operator.clusterserviceversion.yaml
commonAnnotations:
  olm.skipRange: ""
  operators.operatorframework.io/operator-type: standalone
patches:
- patch: '[{"op": "replace", "path": "/spec/replaces", "value": ""}]'
  target:
    kind: ClusterServiceVersion
    name: ocs-consumer-operator.v0.0.0
