name: image-publisher

on:
  workflow_dispatch:
    inputs:
      REGISTRY_NAMESPACE:
        required: true
        default: ocs-dev
      IMAGE_TAG:
        required: true
        default: latest

jobs:
  docker-push:
    name: docker-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Login to Quay
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Build and push docker images
      env:
        REGISTRY_NAMESPACE: ${{ github.event.inputs.REGISTRY_NAMESPACE }}
        IMAGE_TAG: ${{ github.event.inputs.IMAGE_TAG }}
      run: |
        make docker-build docker-push
        make bundle-build bundle-push
        make catalog-build catalog-push
